dist: trusty
sudo: false
language: node_js
node_js: "8.7"
cache: 
  directories:
    - node_modules
script:
- "npm test"
before_deploy:
- "npm i -g uglifyjs"
- "npm run build-public"
deploy:
  provider: pages
  local_dir: "public"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
